apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: split-app-backend
  namespace: flux-system
spec:
  image: ghcr.io/diezfx/split-app-backend
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: split-app-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: split-app-backend
  filterTags:
    pattern: "^main-[a-fA-F0-9]+-(?P<ts>.*)"
    extract: "$ts"
  policy:
    numerical:
      order: asc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: split-app-backend
  namespace: flux-system
spec:
  images:
    - name: ghcr.io/diezfx/split-app-backend
      newTag: main-a58a2b01-1694810962 # {"$imagepolicy": "flux-system:split-app-backend:tag"}
  interval: 5m0s
  path: ./apps/split-app-backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
