apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-app-backend
  labels:
    app: split-app-backend
spec:
  selector:
    matchLabels:
      app: split-app-backend
  template:
    metadata:
      labels:
        app: split-app-backend
      volumes:
        - name: json-configmap-volume
          configMap:
            name: postgres
    spec:
      containers:
        - name: split-app-backend
          image: ghcr.io/diezfx/split-app-backend:main
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/config
              name: json-configmap-volume
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "dev"
