apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nats-ingresss
  labels:
    name: nats-ingresss
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/nats"
            backend:
              service:
                name: nats
                port:
                  number: 8222
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nats-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /nats
