apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - port: 4222
      name: client
    - port: 8222
      name: manage
    - port: 6222
      name: cluster
