---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: split-app-backend
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/split-app-backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
